name = "little-limit-3e90"
main = "src/index.ts"

[env.production]
workers_dev = true
compatibility_flags = []

[[env.production.kv_namespaces]]
binding = "MY_DURABLE_OBJECT"
id = "b36e227f2c814ef6928f68dfad4d0b61"
preview_id = "b36e227f2c814ef6928f68dfad4d0b61"

[[env.production.durable_objects]]
binding = "Globe"
class_name = "Globe"
namespace_id = "my_durable_object_namespace"

[build]
command = "npm run build"
